image: ubuntu:latest

stages:
  - run

mirror:
  stage: run
  only:
    - main
  script:
    - apt update; apt install -y git curl
    - git config --global user.email "gitlab-ci"; git config --global user.name "gitlab-ci"
    - ./mirror-to-gitlab.sh
  only:
    - schedules
    - web
